### ISSUE TITLE
Tweaking the langauge in the People Skills Section 

### ISSUE THREAD

**Issue by bduckles** [jduckles/dsskills#4]
- Consider swapping between the first and second skill groupings for People skills so that the one beginning "Able to effectively..." is in the leftmost column and the one beginning "Visualization, user interface..." is in the second to left column.
In my opinion, the ability to communicate effectively at technical and non technical levels is further along on the mental axis and user interface/experience design etc. is a slightly more global skillset.

- For the section beginning "Visualization..." consider these edits
"Able to build empathy with end-user. User interface/user experience research and design skills such as prototyping, wire frames, personas and data visualization. Interfaces and outputs are relatable and usable."

- Consider edits on the second section
"Actively listens to stakeholders. Able to effectively communicate with technical and non-technical stakeholders. Seeks continuous improvement in verbal, visual and text communications. Comments on code."

- For the third section i suggest these edits:
"Competence in behavioral science skills. Able to build tools and systems that are aware of human behavior, psychology and common cognitive biases."

**Comment by jduckles** [comment]
Changes reflected in https://github.com/jduckles/dsskills/commit/5c0248fe5f974b754dfaef500abf47287401cdcb thanks for contributing @bduckles
